name: Build and release

on:
  push:
    tags:
      - '**'
  workflow_dispatch:
      inputs:
        version:
          required: true
          type: string

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4

    - name: Get asmc
      run: |
        wget https://github.com/ultimate-extract/asmc/releases/latest/download/asmc
        wget https://github.com/ultimate-extract/asmc/releases/latest/download/asmc64
        chmod +x ./*
    
    - name: Build
      run: |
        export PATH="$PWD:$PATH"
        cd CPP/7zip/Bundles/Alone2
        COMPL_STATIC=1 make -j -f ../../cmpl_gcc_x64.mak
        
    - name: Check Tag
      id: check-tag
      run: |
          if [[ "${{ github.ref_name }}" =~ ^[0-9]+\.[0-9]+(\.[0-9]+.*)?$ ]] ; then
              echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          elif [[ "${{ inputs.version }}" =~ ^[0-9]+\.[0-9]+(\.[0-9]+.*)?$ ]] ; then
              echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          else
              echo "SKIPPING RELEASE: '$comment'"
          fi
          
    - name: Release
      uses: softprops/action-gh-release@v2
      if: steps.check-tag.outputs.version
      with:
          tag_name: "v${{ steps.check-tag.outputs.version }}"
          name: "v${{ steps.check-tag.outputs.version }}"
          make_latest: true
          files: |
            CPP/7zip/Bundles/Alone2/b/g_x64/7zzs
            
